annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/rancher-version: '>= 2.10.0'
  catalog.cattle.io/display-name: 'SUSE AI Universal Proxy UI Extension'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 0.1.0
description: "SUSE AI Universal Proxy UI Extension"
name: suseai-rancher-ext
type: application
version: 0.1.0
icon: https://raw.githubusercontent.com/alessandro-festa/up/main/icons/suse-ai-up-ext/0.1.0/0.1.0-icon.svg
