nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.10.0"
    catalog.cattle.io/ui-extensions-version: "0.1.0"
