apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suse-ai-up.fullname" . }}
  labels:
    {{- include "suse-ai-up.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "suse-ai-up.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "suse-ai-up.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          image: {{ include "suse-ai-up.image" . }}
          ports:
            - containerPort: {{ .Values.services.proxy.port }}
          env:
            - name: PROXY_PORT
              value: "{{ .Values.services.proxy.port }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.cors.allowedOrigins }}"
        - name: registry
          image: {{ include "suse-ai-up.image" . }}
          ports:
            - containerPort: {{ .Values.services.registry.port }}
          env:
            - name: REGISTRY_PORT
              value: "{{ .Values.services.registry.port }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.cors.allowedOrigins }}"
        - name: discovery
          image: {{ include "suse-ai-up.image" . }}
          ports:
            - containerPort: {{ .Values.services.discovery.port }}
          env:
            - name: DISCOVERY_PORT
              value: "{{ .Values.services.discovery.port }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.cors.allowedOrigins }}"
        - name: plugins
          image: {{ include "suse-ai-up.image" . }}
          ports:
            - containerPort: {{ .Values.services.plugins.port }}
          env:
            - name: PLUGINS_PORT
              value: "{{ .Values.services.plugins.port }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.cors.allowedOrigins }}"