{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sidecar.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "suse-ai-up.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}