{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "suse-ai-up.fullname" . }}-cluster-binding
  labels:
    {{- include "suse-ai-up.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "suse-ai-up.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "suse-ai-up.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "suse-ai-up.fullname" . }}-sidecar-binding
  namespace: {{ .Values.sidecar.namespace }}
  labels:
    {{- include "suse-ai-up.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "suse-ai-up.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "suse-ai-up.fullname" . }}-sidecar-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}