apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suse-ai-up.fullname" . }}-auth
  labels:
    {{- include "suse-ai-up.labels" . | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.auth.mode "github" }}
  github-client-secret: {{ .Values.auth.github.clientSecret | b64enc | quote }}
{{- end }}
{{- if eq .Values.auth.mode "rancher" }}
  rancher-client-secret: {{ .Values.auth.rancher.clientSecret | b64enc | quote }}
{{- end }}